stages:
- build
- deploy_test
- deploy_production

build:
    stage: build
    script:
        - docker build -t youyou/base .
    tags:
        - youyou

deploy_test:
    stage: deploy_test
    only:
        - develop
    script:
        - hostname
        #- docker build -t youyou/test --target=test .
    tags:
        - youyou

deploy_production:
    stage: deploy_production
    only:
    - master
    script:
       - docker build -t youyou/prod-admin --target=admin .
       - docker build -t youyou/prod-api --target=api .
       - docker build -t youyou/prod-website --target=website .
       - docker build -t youyou/prod-cli --target=cli .
    tags:
        - youyou