stages:
- build
- deploy_test
- deploy_production

build:
    stage: build
    script:
        - docker build -t php-yaf-mongodb/base --target=base .
    tags:
        - youyou

deploy_test:
    stage: deploy_test
    only:
        - develop
    script:
        - docker build -t php-yaf-mongodb/test --target=test .
    tags:
        - youyou

deploy_production:
    stage: deploy_production
    only:
    - master
    script:
       - hostname
    tags:
        - youyou